# -*- coding: utf-8 -*-
"""2504

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-gCdMTlmF904mOcJGiN8ILcSgo6o7VS
"""

openBracket = ['(', '[']
closeBracket = [')', ']']

def _2504() :
  brackets = input() 
  stack = []

  for bracket in brackets :
    if bracket in openBracket :
      stack.append(bracket)
    
    elif bracket in closeBracket :
      if not stack :
        return 0
      last = stack.pop()
      temp = 0
      while last != '(' and last != '[' :
        temp += last
        if stack : last = stack.pop()
        else : return 0
      if temp == 0 : temp = 1

      if bracket == ')' and last == '(' :
        stack.append(2*temp)
      elif bracket == ']' and last == '[' :
        stack.append(3*temp)
      else : 
        return 0
  
  tot = 0
  if stack :
    for node in stack :
      if node not in openBracket+closeBracket :
        tot += node 
      else :
        return 0

  return tot

print(_2504())