# -*- coding: utf-8 -*-
"""9012

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-gCdMTlmF904mOcJGiN8ILcSgo6o7VS
"""

def _9012() :
  T = int(input())

  for _ in range(T) :
    brackets = input()
    stack = []
    VPS = True
    for bracket in brackets :
      if bracket == '(' :
        stack.append(bracket)
      elif bracket == ')' :
        if not stack :
          VPS = False
          break
        last = stack.pop()
        if last != '(' :
          VPS = False
          break
    if not VPS or stack :
      print("NO")
    else :
      print("YES")


_9012()