# -*- coding: utf-8 -*-
"""프로그래머스_프린터

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V-gCdMTlmF904mOcJGiN8ILcSgo6o7VS
"""

# 중요도가 높은 문서를 먼저 인쇄한다.
# 문서    A B C D
# 순위    2 1 3 2 (클 수록 높음)
# 내꺼        2

# C
from collections import deque 

def solution(priorities, location) :
    workCnt = 0
    
    sortedPrior = sorted(priorities)
    
    printer = deque([])
    for idx, pri in enumerate(priorities) :
        printer.append([pri,idx])
    
    # print(sortedPrior)
    while printer :
        nextPaper = printer.popleft()
        # print(nextPaper, sortedPrior)
        if sortedPrior[-1] == nextPaper[0] :
            workCnt += 1
            sortedPrior.pop()
            if nextPaper[1] == location :
                return workCnt
        else :
            printer.append(nextPaper)
    
    return workCnt