# -*- coding: utf-8 -*-
"""네트워크

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JU3LAI7zYXs48A4BqjnybwV-yc-qQJs2
"""

def solution(n, computers):
    answer = 0
    visited = [False]*n
    
    def dfs(start) :
        st = [start]
        while st :
            com_num = st.pop()
            if not visited[com_num] :
                visited[com_num] = 1
            for i in range(len(computers[0])) :
                if computers[com_num][i] == 1 and not visited[i]:
                    st.append(i)
                    
    i = 0
    while 0 in visited :
        if visited[i] == 0:
            dfs(i)
            answer += 1
        i+=1
        
    return answer