# -*- coding: utf-8 -*-
"""2606바이러스

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pzTrG_Y0kjYUz6-ddK643SRLtXX-_-Pa
"""

# start==1가 주어질 때 연결된 노드의 수를 구하라 (start는 제외한다)

def addNode(first, second, nodeList) :
  if first in nodeList :
    nodeList[first].append(second)
  else :
    nodeList[first] = [second]
  return nodeList

def _2606() :
  computerN = int(input())
  computerPairNum = int(input())
  nodeList = {}
  # make nodes
  for _ in range(computerPairNum) :
    first, second = map(int, input().split(' '))
    nodeList = addNode(first,second,nodeList)
    nodeList = addNode(second,first,nodeList)
    
  # dfs
  visited = []
  stack = [1] # start node
  while stack :
    node = stack.pop()
    if node not in visited and node in nodeList : # node가 nodeList에 key로 존재
      visited.append(node)
      stack += list(set(nodeList[node]) - set(visited))
  # print(visited)
  return len(visited)-1

print(_2606())

6