# -*- coding: utf-8 -*-
"""프로그래머스_타겟넘버(조예린)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TX2XSWDcsV67NvMtMjIdxtgPabKH6bFd
"""

from collections import deque

def solution(numbers, target):
    answer=0
    q = deque([0])
    
    for number in numbers :     
        tempLen = len(q)
        for i in range(0,tempLen) :
            n = q.popleft()
            q.append(n+number)
            q.append(n-number)
        # print(q)
        
    q = list(q) # python스러운 메소드들 문제풀면서 답코드 한번 찾아보고 기억해두기
    return q.count(target) # count 쓰기! find, count