# -*- coding: utf-8 -*-
"""프로그래머스_위장(조예린)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10s8FAFluiERnHqjN07NOMFNfhLtrv9nw
"""

def solution(clothes):
    answer = 1
    closet = {}
    
    # 갯수 구하기
    for cloth in clothes :
        clothType = cloth[1]
        if clothType in closet :
            closet[clothType] += 1
        else :
            closet[clothType] = 1
    
    # 모든 경우의 수 - 공집합(=1)
    # A, B, C면 (A+1)*(B+1)*(C+1)-1
    for clothType in closet :
        answer *= (closet[clothType]+1)
        
    return answer-1